FROM nginx:latest
RUN apt update -y && apt upgrade -y 
VOLUME /home/dimas/DevOPS/Docker/nginx-cont/docker_dir/nginx-conf:/etc/nginx/nginx.conf
#RUN mkdir /git_repo 
#WORKDIR /git_repo
#ENTRYPOINT ["git", "clone"] 
#CMD ["https://github.com/85Dimas85/DevOPS.git"]
