---
- name: add user dimas with all grants
  hosts: servers

#  vars:
#    ansible_python_interpreter: "/usr/bin/python2.7"

  pre_tasks:
  - name: install python2 
    raw: "apt-get install -y python" 
  
  roles:
  - dimas-add-user
  - dimas-add-sudo
  - dimas-add-rsa-key

  - install-usefull-pkg
 
